const ItemDataBase = [
  {
    id: 1,
    title: "Premezcla",
    price: 200,
    category: "Almacen",
    stock: 4,
    imgProducts: "/imgs/Premezcla.png",
  },
  {
    id: 2,
    title: "Azucar",
    price: 150,
    category: "Almacen",
    stock: 3,
    imgProducts: "/imgs/Azucar.png",
  },
  {
    id: 3,
    title: "Polvo de hornear",
    price: 133,
    category: "Almacen",
    stock: 1,
    imgProducts: "/imgs/Polvo de Hornear.png",
  },
  {
    id: 4,
    title: "Pan",
    price: 250,
    category: "Panificados",
    stock: 6,
    imgProducts: "/imgs/pan.png",
  },
  {
    id: 5,
    title: "Masa de tarta",
    price: 150,
    category: "Congelados",
    stock: 1,
    imgProducts: "/imgs/Masa de tarta.png",
  },
  {
    id: 6,
    title: "Masa de empanadas",
    price: 140,
    category: "Congelados",
    stock: 2,
    imgProducts: "/imgs/EmpanadasLibredeGlutenNuevo.png",
  },
  {
    id: 7,
    title: "Helado",
    price: 130,
    category: "Congelado",
    stock: 7,
    imgProducts: "/imgs/helado.png",
  },
  {
    id: 8,
    title: "Sorrentinos JyQ",
    price: 250,
    category: "Congelados",
    stock: 8,
    imgProducts: "/imgs/SorrentinosJyQ}.png",
  },
  {
    id: 9,
    title: "Ñoquis",
    price: 185,
    category: "Congelados",
    stock: 4,
    imgProducts: "/imgs/Ñoquis.png",
  },
  {
    id: 10,
    title: "Crackers",
    price: 300,
    category: "Almacen",
    stock: 6,
    imgProducts: "/imgs/crackers_scha.png",
  },
];

export default ItemDataBase;
